version: "3.9"

services:
  database:
    image: postgres
    container_name: bank-api-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bank-api
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local